services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - integration-network
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - integration-network
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - integration-network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

networks:
  integration-network:
    driver: bridge

volumes:
  frontend_node_modules:
  redis_data: